wi_minor = {
"Feather token, anchor",
"Universal solvent",
"Elixir of love",
"Unguent of timelessness",
"Feather token, fan",
"Dust of tracelessness",
"Elixir of hiding",
"Elixir of tumbling",
"Elixir of swimming",
"Elixir of vision",
"Silversheen",
"Feather token, bird",
"Feather token, tree",
"Feather token, swan boat",
"Elixir of truth",
"Feather token, whip",
"Dust of dryness",
"Hand of the mage",
"Bracers of armor +1",
"Cloak of resistance +1",
"Pearl of power, 1st-level spell",
"Phylactery of faithfulness",
"Salve of slipperiness",
"Elixir of fire breath",
"Pipes of the sewers",
"Dust of illusion",
"Brooch of shielding",
"Necklace of fireballs type I",
"Dust of appearance",
"Hat of disguise",
"Pipes of sounding",
"Efficient quiver",
"Amulet of natural armor +1",
"Handy haversack",
"Horn of fog",
"Elemental gem",
"Robe of bones",
"Sovereign glue",
"Bag of holding type I",
"Boots of elvenkind",
"Boots of the winterlands",
"Candle of truth",
"Cloak of elvenkind",
"Eyes of the eagle",
"Goggles of minute seeing",
"Scarab, golembane",
"Necklace of fireballs type II",
"Stone of alarm",
"Bead of force",
"Chime of opening",
"Horseshoes of speed",
"Rope of climbing",
"Bag of tricks, gray",
"Dust of disappearance",
"Lens of detection",
"Vestment, druid's",
"Figurine of wondrous power, silver raven",
"Amulet of mighty fists +1",
"Belt of giant strength +2",
"Belt of incredible dexterity +2",
"Belt of mighty constitution +2",
"Bracers of armor +2",
"Cloak of resistance +2",
"Gloves of arrow snaring",
"Headband of alluring charisma +2",
"Headband of inspired wisdom +2",
"Headband of vast intelligence +2",
"Ioun stone, clear spindle",
"Restorative ointment",
"Marvelous pigments",
"Pearl of power, 2nd-level spell",
"Stone salve",
"Necklace of fireballs type III",
"Circlet of persuasion",
"Slippers of spider climbing",
"Incense of meditation",
"Bag of holding type II",
"Bracers of archery, lesser",
"Ioun stone, dusty rose prism",
"Helm of comprehend languages and read magic",
"Vest of escape",
"Eversmoking bottle",
"Sustaining spoon",
"Necklace of fireballs type IV",
"Boots of striding and springing",
"Wind fan",
"Necklace of fireballs type V",
"Horseshoes of a zephyr",
"Pipes of haunting",
"Gloves of swimming and climbing",
"Crown of blasting, minor",
"Horn of goodness/evil",
"Robe of useful items",
"Boat, folding",
"Cloak of the manta ray",
"Bottle of air",
"Bag of holding type III",
"Periapt of health",
"Boots of levitation",
"Harp of charming"
}

wi_medium = {
"Amulet of natural armor +2",
"Golem manual, flesh",
"Hand of glory",
"Ioun stone, deep red sphere",
"Ioun stone, incandescent blue sphere",
"Ioun stone, pale blue rhomboid",
"Ioun stone, pink and green sphere",
"Ioun stone, pink rhomboid",
"Ioun stone, scarlet and blue sphere",
"Deck of illusions",
"Necklace of fireballs type VI",
"Candle of invocation",
"Robe of blending",
"Bag of tricks, rust",
"Necklace of fireballs type VII",
"Bracers of armor +3",
"Cloak of resistance +3",
"Decanter of endless water",
"Necklace of adaptation",
"Pearl of power, 3rd-level spell",
"Figurine of wondrous power, serpentine owl",
"Strand of prayer beads, lesser",
"Bag of holding type IV",
"Belt of physical might +2",
"Figurine of wondrous power, bronze griffon",
"Figurine of wondrous power, ebony fly",
"Glove of storing",
"Headband of mental prowess +2",
"Ioun stone, dark blue rhomboid",
"Cape of the mountebank",
"Phylactery of negative channeling",
"Phylactery of positive channeling",
"Gauntlet of rust",
"Boots of speed",
"Goggles of night",
"Golem manual, clay",
"Medallion of thoughts",
"Blessed book",
"Gem of brightness",
"Lyre of building",
"Robe, Monk's",
"Cloak of arachnida",
"Belt of dwarvenkind",
"Periapt of wound closure",
"Pearl of the sirines",
"Figurine of wondrous power, onyx dog",
"Amulet of mighty fists +2",
"Bag of tricks, tan",
"Belt of giant strength +4",
"Belt of incredible dexterity +4",
"Belt of mighty constitution +4",
"Belt of physical perfection +2",
"Boots, winged",
"Bracers of armor +4",
"Cloak of resistance +4",
"Headband of alluring charisma +4",
"Headband of inspired wisdom +4",
"Headband of mental superiority +2",
"Headband of vast intelligence +4",
"Pearl of power, 4th-level spell",
"Scabbard of keen edges",
"Figurine of wondrous power, golden lions",
"Chime of interruption",
"Broom of flying",
"Figurine of wondrous power, marble elephant",
"Amulet of natural armor +3",
"Ioun stone, iridescent spindle",
"Bracelet of friends",
"Carpet of flying, 5 ft. by 5 ft.",
"Horn of blasting",
"Ioun stone, pale lavender ellipsoid",
"Ioun stone, pearly white spindle",
"Portable hole",
"Stone of good luck (luckstone)",
"Figurine of wondrous power, ivory goats",
"Rope of entanglement",
"Golem manual, stone",
"Mask of the skull",
"Mattock of the titans",
"Crown of blasting, major",
"Cloak of displacement, minor",
"Helm of underwater action",
"Bracers of archery, greater",
"Bracers of armor +5",
"Cloak of resistance +5",
"Eyes of doom",
"Pearl of power, 5th-level spell",
"Maul of the titans",
"Cloak of the bat",
"Iron bands of binding",
"Cube of frost resistance",
"Helm of telepathy",
"Periapt of proof against poison",
"Robe of scintillating colors",
"Manual of bodily health +1",
"Manual of gainful exercise +1",
"Manual of quickness in action +1",
"Tome of clear thought +1",
"Tome of leadership and influence +1",
"Tome of understanding +1"
}

wi_major = {
"Dimensional shackles",
"Figurine of wondrous power, obsidian steed",
"Drums of panic",
"Ioun stone, orange prism",
"Ioun stone, pale green prism",
"Lantern of revealing",
"Amulet of natural armor +4",
"Amulet of proof against detection and location",
"Carpet of flying, 5 ft. by 10 ft.",
"Golem manual, iron",
"Amulet of mighty fists +3",
"Belt of giant strength +6",
"Belt of incredible dexterity +6",
"Belt of mighty constitution +6",
"Bracers of armor +6",
"Headband of alluring charisma +6",
"Headband of inspired wisdom +6",
"Headband of vast intelligence +6",
"Ioun stone, vibrant purple prism",
"Pearl of power, 6th-level spell",
"Scarab of protection",
"Belt of physical might +4",
"Headband of mental prowess +4",
"Ioun stone, lavender and green ellipsoid",
"Ring gates",
"Crystal ball",
"Golem manual, stone guardian",
"Strand of prayer beads",
"Orb of storms",
"Boots of teleportation",
"Bracers of armor +7",
"Pearl of power, 7th-level spell",
"Amulet of natural armor +5",
"Cloak of displacement, major",
"Crystal ball with see invisibility",
"Horn of Valhalla",
"Crystal ball with detect thoughts",
"Wings of flying",
"Cloak of etherealness",
"Instant fortress",
"Manual of bodily health +2",
"Manual of gainful exercise +2",
"Manual of quickness in action +2",
"Tome of clear thought +2",
"Tome of leadership and influence +2",
"Tome of understanding +2",
"Eyes of charming",
"Robe of stars",
"Carpet of flying, 10 ft. by 10 ft.",
"Darkskull",
"Cube of force",
"Amulet of mighty fists +4",
"Belt of physical perfection +4",
"Bracers of armor +8",
"Headband of mental superiority +4",
"Pearl of power, 8th-level spell",
"Crystal ball with telepathy",
"Horn of blasting, greater",
"Pearl of power, two spells",
"Helm of teleportation",
"Gem of seeing",
"Robe of the archmagi",
"Mantle of faith",
"Crystal ball with true seeing",
"Pearl of power, 9th-level spell",
"Well of many worlds",
"Manual of bodily health +3",
"Manual of gainful exercise +3",
"Manual of quickness in action +3",
"Tome of clear thought +3",
"Tome of leadership and influence +3",
"Tome of understanding +3",
"Apparatus of the crab",
"Belt of physical might +6",
"Headband of mental prowess +6",
"Mantle of spell resistance",
"Mirror of opposition",
"Strand of prayer beads, greater",
"Amulet of mighty fists +5",
"Manual of bodily health +4",
"Manual of gainful exercise +4",
"Manual of quickness in action +4",
"Tome of clear thought +4",
"Tome of leadership and influence +4",
"Tome of understanding +4",
"Amulet of the planes",
"Robe of eyes",
"Helm of Brilliance",
"Manual of bodily health +5",
"Manual of gainful exercise +5",
"Manual of quickness in action +5",
"Tome of clear thought +5",
"Tome of leadership and influence +5",
"Tome of understanding +5",
"Belt of physical perfection +6",
"Headband of mental superiority +6",
"Efreeti bottle",
"Cubic gate",
"Iron flask",
"Mirror of life trapping"
}